name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create Tag
        id: tag
        run: |
          git config --global user.email "amgad@yahoo.com"
          git config --global user.name "amgadabdelhafez"
          git tag -a v${{ github.run_number }} -m "Release v${{ github.run_number }}"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/amgadabdelhafez/plugin.video.skipintro.git v${{ github.run_number }}

      - name: Verify Tag
        run: |
          git fetch --tags
          git tag --list

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: plugin.video.skipintro-*.zip
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Release File
        run: |
          mv plugin.video.skipintro-*.zip release/

      - name: Commit and Push Changes
        run: |
          git add release/plugin.video.skipintro-*.zip
          git commit -m "Move release file to release directory [skip ci]"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/amgadabdelhafez/plugin.video.skipintro.git master
